In [30]:
import numpy as np

u = np.array([2 ,-7 ,1])
v = np.array([-3,0,4])
A = np.array([[1,2,0], [3, -1, 4]])
B = np.array([[2,-1], [1,0],[-3,4]])

<p>1.A</p>

In [52]:
print(u+v) # Correct

[-1 -7  5]


<p>1.B</p>

In [55]:
print(-3 + u) # Scala (incorrect)
print(-3 * u) # (correct)

[ -1 -10  -2]
[-6 21 -3]


In [56]:
#1.C
print(u*v) # Matrix MUltiplication (Incorrect)
np.dot(u, v) # (correct)

[-6  0  4]


np.int64(-2)

In [57]:
#1.D
print(u*u) # Matrix (Same as above)
np.dot(u, u) # (correct)

[ 4 49  1]


np.int64(54)

In [59]:
#1.E
print(np.sqrt(u*u)) # Matrix (Incorrect)
np.sqrt(np.dot(u, u)) # (correct)

[2. 7. 1.]


np.float64(7.3484692283495345)

In [60]:
#1.F U * V
#u.transpose() # Hadarmard Product (NO need to transpose)
print(u*v)

[-6  0  4]


In [61]:
#1.G Matrix Addition
print(A**2) # Incorrect
print(A + A) # (correct)

[[ 1  4  0]
 [ 9  1 16]]
[[ 2  4  0]
 [ 6 -2  8]]


In [62]:
#1.H
u + A # This is incorrect (should've crashed) numpy duplicates (broadcasting)

array([[ 3, -5,  1],
       [ 5, -8,  5]])

In [25]:
#1.I
print(10*A) # correct

[[ 10  20   0]
 [ 30 -10  40]]


In [64]:
#1.J
print(v * A) # incorrect
np.dot(A, v)

[[-3  0  0]
 [-9  0 16]]


array([-3,  7])

In [67]:
#1.K
A.T * B # Incorrect
np.dot(A, B)

array([[ 4, -1],
       [-7, 13]])

In [44]:
#1.L
A.T

array([[ 1,  3],
       [ 2, -1],
       [ 0,  4]])

In [46]:
#1.M
np.dot(A, A.T) # Correct

array([[ 5,  1],
       [ 1, 26]])

In [68]:
#1.N
np.dot(A.T, A) # Correct

array([[10, -1, 12],
       [-1,  5, -4],
       [12, -4, 16]])

In [49]:
#1.O
np.min(u)

np.int64(-7)

In [50]:
#1.P
np.mean(u)

np.float64(-1.3333333333333333)

In [ ]:
x = np.array([1,2,3,4])
x.cumsum()

def cumsum():
    

In [73]:
x = np.arrange(1,101)
%timeit np.cumsum(x)

AttributeError: module 'numpy' has no attribute 'arrange'

In [69]:
x = list(range(1,101))
%timeit cumsum(x)

NameError: name 'cumsum' is not defined